version: '3.8'
services:
  web-app:
    build: ./web-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.7.11
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2

  telegraf:
    image: telegraf:1.34.2
    volumes:
      - ./monitoring-stack/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_ETC=/hostfs/etc
    user: "0:0"
    privileged: true
    depends_on:
      - influxdb
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    volumes:
      - "./monitoring-stack/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./monitoring-stack/prometheus/targets.json:/etc/prometheus/targets.json"
    #networks:
    #  - localprom
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
    
networks:
  localprom:
    driver: bridge

secrets:
  influxdb2-admin-username:
    file: ~/.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ~/.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: ~/.env.influxdb2-admin-token

volumes:
  influxdb2-data:
  influxdb2-config:
  grafana_data: