global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'windows'
    static_configs:
      - targets: ['172.27.160.1:9182'] 

  - job_name: 'linux'
    static_configs:
      - targets: ['node-exporter:9100']