global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dynamic-nodes'
    file_sd_configs:
      - files:
        - /etc/prometheus/targets.json
        refresh_interval: 30s